# ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████
#░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░
#
#     ██████          █████             █████████                      █████                             █████  █████
#   ███░░░░███       ░░███             ███░░░░░███                    ░░███                             ░░███  ░░███
#  ███    ░░███       ░███            ███     ░░░  █████ ████  █████  ███████    ██████  █████████████   ░███  ███████    ██████  █████████████    █████
# ░███     ░███       ░███           ░███         ░░███ ░███  ███░░  ░░░███░    ███░░███░░███░░███░░███  ░███ ░░░███░    ███░░███░░███░░███░░███  ███░░
# ░███   ██░███       ░███           ░███          ░███ ░███ ░░█████   ░███    ░███ ░███ ░███ ░███ ░███  ░███   ░███    ░███████  ░███ ░███ ░███ ░░█████
# ░░███ ░░████  ███   ░███           ░░███     ███ ░███ ░███  ░░░░███  ░███ ███░███ ░███ ░███ ░███ ░███  ░███   ░███ ███░███░░░   ░███ ░███ ░███  ░░░░███
# ░░░██████░██░░████████   █████████ ░░█████████  ░░████████ ██████   ░░█████ ░░██████  █████░███ █████ █████  ░░█████ ░░██████  █████░███ █████ ██████
# ░░░░░░ ░░  ░░░░░░░░   ░░░░░░░░░   ░░░░░░░░░    ░░░░░░░░ ░░░░░░     ░░░░░   ░░░░░░  ░░░░░ ░░░ ░░░░░ ░░░░░    ░░░░░   ░░░░░░  ░░░░░ ░░░ ░░░░░ ░░░░░░
#
#  ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████ ██████████
# ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░ ░░░░░░░░░░

Prefix: "§6QJ_C§3ustom§6I§3tems §6- "
Version: 1.2.3
Main_Options:
  Silkspawner:
    Require_pickaxe: true
    Require_silktouch: true
  Undeadsword:
    Damagemultiplier:
      Zombie: 25
      Skeleton: 35