name: QJ_CustomItems
version: 1.4.1
main: fr.qjwin.qj_customitems.Main
api-version: 1.16
authors: [ QJWIN ]
softdepend: [HolographicDisplays]
description: Personal plugin for items with specials effects
permissions:
  silkspawner.allowdrop:
    description: Lets the player use spawner system.
    default: true
  trashcan.use:
    description: Lets the player use trashcan system.
    default: true
  home.global:
    description: Lets the player use setthome and home system.
    default: true
  backpacks.use:
    description: Lets the player use backpacks system.
    default: true
commands:
  Give_Backpack:
    description: give a Backpack to the player.
    usage: /<command>
  sethome:
    description: set a home for the player.
    usage: /<command>
  home:
    description: teleport the player to is home.
    usage: /<command>
  Give_GrapplingHook:
    description: give a grappling hook to the player.
    usage: /<command>
  Give_TeleportSword:
    description: give a teleport sword to the player.
    usage: /<command>
  Give_ServerGift:
    description: give a admin surprise to the player.
    usage: /<command>
  Give_ExplosiveBow:
    description: give a explosive bow to the player.
    usage: /<command>
  Give_InfiniteWaterBucket:
    description: give a infinite waterbucket to the player.
    usage: /<command>
  Give_InfiniteLavaBucket:
    description: give a infinite lavabucket to the player.
    usage: /<command>
  Give_MachineGunBow:
    description: give a machine gun bow to the player.
    usage: /<command>
  Give_MultiBreakPickaxe:
    description: give a multiBreak pickaxe to the player.
    usage: /<command>
  Give_CresusPickaxe:
    description: give a cresus pickaxe to the player.
    usage: /<command>
  Give_Boomerang:
    description: give a Boomerang to the player.
    usage: /<command>
  Give_HomingBow:
    description: give a HomingBow to the player.
    usage: /<command>
  Give_ThrowingAxe:
    description: give a ThrowingAxe to the player.
    usage: /<command>
  Give_UndeadSword:
    description: give a UndeadSword to the player.
    usage: /<command>
  Give_Dynamite:
    description: give a Dynamite to the player.
    usage: /<command>
  Give_LightingSword:
    description: give a LightingSword to the player.
    usage: /<command>
  Give_AutoSmeltPickaxe:
    description: give a AutoSmeltPickaxe to the player.
    usage: /<command>
  Give_FireBall:
    description: give a FireBall to the player.
    usage: /<command>
  Give_Grenade:
    description: give a Grenade to the player.
    usage: /<command>
  Give_HermesShoes:
    description: give a HermesShoes to the player.
    usage: /<command>
  Give_Landmine:
    description: give a Landmine to the player.
    usage: /<command>
  Give_InfiniteEmptyBucket:
    description: give a InfiniteEmptyBucket to the player.
    usage: /<command>
  Give_Potion_haste_1:
    description: give a haste 1 potion to the player.
    usage: /<command>
  Give_Potion_haste_2:
    description: give a haste 2 potion to the player.
    usage: /<command>
  Give_Potion_haste_3:
    description: give a haste 3 potion to the player.
    usage: /<command>
  Give_Potion_luck_1:
    description: give a luck 1 potion to the player.
    usage: /<command>
  Give_Potion_luck_2:
    description: give a luck 2 potion to the player.
    usage: /<command>
  Give_Potion_luck_3:
    description: give a luck 3 potion to the player.
    usage: /<command>
  Give_Potion_Resistance_1:
    description: give a resistance 1 potion to the player.
    usage: /<command>
  Give_Potion_Beauty_1:
    description: give a Beauty 1 potion to the player.
    usage: /<command>
  Give_Potion_Saturation_1:
    description: give a Saturation 1 potion to the player.
    usage: /<command>
  Give_Potion_Absorption_1:
    description: give a Absorption 1 potion to the player.
    usage: /<command>
  Give_Potion_HealBoost_1:
    description: give a HealBoost 1 potion to the player.
    usage: /<command>
  Give_Potions:
    description: give all potions to the player.
    usage: /<command>
  Give_Hat_Farmer:
    description: give a Hat_Farmer to the player.
    usage: /<command>
  Give_Hat_Arrow:
    description: give a Hat_Arrow to the player.
    usage: /<command>
  Give_Hat_Fes:
    description: give a Hat_Fes to the player.
    usage: /<command>
  Give_Hat_Indian:
    description: give a Hat_Indian to the player.
    usage: /<command>
  Give_Hat_Dandy_RED:
    description: give a Hat_Dandy_RED to the player.
    usage: /<command>
  Give_Hat_Dandy_LBLUE:
    description: give a Hat_Dandy_LBLUE to the player.
    usage: /<command>
  Give_Hat_Dandy_YELLOW:
    description: give a Hat_Dandy_YELLOW to the player.
    usage: /<command>
  Give_Hat_Dandy_LIME:
    description: give a Hat_Dandy_LIME to the player.
    usage: /<command>
  Give_Hat_Dandy_RAINBOW:
    description: give a Hat_Dandy_RAINBOW to the player.
    usage: /<command>
  Give_Hat_Dandy_GLASS:
    description: give a Hat_Dandy_GLASS to the player.
    usage: /<command>
  Give_Hat_Squid:
    description: give a Hat_Squid to the player.
    usage: /<command>
  Give_Hats:
    description: give all Hat to the player.
    usage: /<command>
  Give_TrashCan:
    description: give a TrashCan to the player.
    usage: /<command>